### ISSUE TITLE
"Job - Help me with my son" is missing a location square

### ISSUE THREAD

**Issue by DJChupa13** [MisterIbis/MMBN3_AP_Tracker#6]
The second step in `Job - Help me with my son` is present in `Job Board (Other regions)` when it is inspected in Overworld Locations > SciLab.  However, the actual location where step 2 takes place does not have a location square corresponding to it.

This location is at a purple Navi NPC in ACDC 3, next to the screen transition arrow that takes you to ACDC 2, as shown [here](https://shrines.rpgclassics.com/gba/mmbn3/jobs.shtml).

**Comment by MisterIbis** [comment]
There was a typo on the map name for that location that prevented it from displaying correctly. It's now resolved with 0.2.0.7
