### ISSUE TITLE
"Job: Help With a Will" check is not synced between AP and Poptracker

### ISSUE THREAD

**Issue by DJChupa13** [MisterIbis/MMBN3_AP_Tracker#7]
See Screenshot for clarity: [https://imgur.com/rLYM9sY](https://imgur.com/rLYM9sY)

Basically, the item flag for `Job - Help with a Will - Finish (Kid Outside 5A)` is not correctly syncing up with Archipelago while the AP mode is Online in Poptracker.  In the screenshot, on the left, you can see that the item from the job has already been checked.  In game, the little girl has already given me the item here, and now her dialogue reads "I'll treasure this photo forever..." indicating that the questline is complete.

If the item flag is manually cleared, if I re-sync to AP, the item state is reset back to available.

**Comment by DJChupa13** [comment]
`Job: Looking for condor` has the exact same issue.

**Comment by MisterIbis** [comment]
Both were resolved with 0.2.0.8, and  auto-updates to that should be functional now as well.
